name: Actions Workflow (po)

on:
  push:
  pull_request:
    types: [closed, assigned,
    opened, reopened]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls -a 
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
        # git clonse git@github:$GITHUB_REPOSITORY
          # git checkout 
      - name: Checkout (po)
        uses: actions/checkout@v1 #will authenticate to your repo, fetch the code and checkout into the 
                                  ##commit that triggered the workflow
      - name: List Files After Checkout 
        run: |
          pwd
          ls -a 
      - name: Simple JS Action   ##commit that triggered the workflow
        id: greet
        uses: actions/hello-world-javascript-action@v1 ##or branch version/or commit ID
        with:    ##how to provide an input with an action? is with the WITH key 
          who-to-greet: John 
          ##actions can also produce an output. "Hello ____"
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"    ##in order to output name (in SJSAction) you need tp
                                